# .travis.yml -- Travis CI configuration for the MPS
# $Id$

# Some branches don't need builds.  Add them here to avoid using build
# resources and unnecessary build messages.  See
# <https://docs.travis-ci.com/user/conditions-v1>.
if: NOT branch IN (branch/2023-01-11/github-ci)

# The main build matrix for POSIX-like systems.
language: c # see <https://docs.travis-ci.com/user/languages/c/>.
os:
  - freebsd
  - linux
  # If you include macOS here, Travis launches a redundant build on
  # amd64, even though we specify arm64.  Perhaps it's because they
  # don't support macOS on arm64.  When they do, try uncommenting
  # this.
  # - osx
  # See "include" section for Windows
arch:
  # Most amd64 builds moved to GitHub CI.  See .github/workflows/c-cpp.yml.
  # - amd64
  - arm64
compiler:
  - clang
  - gcc
script:
- ./configure --prefix=$PWD/prefix && make install && make test

matrix:
  # Extra build jobs to add to the matrix
  include:
    # GitHub CI does not provide FreeBSD <https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources>.
    - os: freebsd
      arch: amd64
      compiler: clang
    - os: freebsd
      arch: amd64
      compiler: gcc
    # Windows moved to GitHub CI.  See .github/workflows/c-cpp.yml.
    #  - os: windows
    #    arch: amd64
    #    compiler: clang # This is a lie since we invoke MV (Microsoft C)
    #    script: MSYS2_ARG_CONV_EXCL='*' cmd /c 'code\w3i6mv.bat'
  # Specific combinations to exclude from the matrix
  exclude:
    - os: osx
      compiler: gcc

notifications:
  email:
    - mps-travis@ravenbrook.com

# This shows how you can ask Travis to install or update packages.
#before_install:
#  - if test "$TRAVIS_OS_NAME" = "linux"; then sudo apt-get -qq update; fi
#  - if test "$TRAVIS_OS_NAME" = "linux"; then sudo apt-get install -y gcc-4.7; fi
